spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dharani
    username: root
    password: Tiger
    driver-class-name: com.mysql.cj.jdbc.Driver  # Correct class name
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 5702

